### ISSUE TITLE
Eliminar logs

### ISSUE THREAD

**Issue by castromaciel** [eliasjuliana/final-project-be#12]
Para una estructura de proyecto mucho más limpia, se recomienda eliminar todos los logs que son para el desarrollador. Ya que estos, pueden estar devolviendo información sensible

<img width="900" alt="image" src="https://github.com/eliasjuliana/final-project-be/assets/83432755/bd24444b-3274-4ccc-ac0a-7da1287ca305">

**Comment by CardozoMartin** [comment]
https://github.com/eliasjuliana/final-project-be/commit/1fafd53589f8bd5cad796e66b279a5bacf5df088 .Adjunto el commit donde se hizo la limpieza del codigo de todos los console.log
